import type {
  ActivityList,
  ProjectList,
  Settings,
  SystemSummary,
} from "@devpulse/shared-types";
import type { DataProvider } from "../providers/contracts";

export const systemSummary: SystemSummary = {
  cpu_percent: 42,
  logical_processors: 8,
  memory_percent: 61,
  memory_available_bytes: 8_000_000_000,
  disk_percent: 37,
  volumes: [{ mount: "C:\\", usage_percent: 37, free_bytes: 100_000_000_000 }],
  process_uptime_seconds: 120,
  scan_worker_status: "idle",
  cache_status: "ready",
  application_data_location: "C:\\Temp\\DevPulse",
  log_directory_location: "C:\\Temp\\DevPulse\\logs",
  repositories_total: 1,
  clean_repositories: 1,
  modified_repositories: 0,
  repositories_with_warnings: 0,
  average_health_score: 86,
  last_successful_refresh: "2026-07-16T10:00:00Z",
  refreshing: false,
};

export const projects: ProjectList = {
  total: 1,
  last_successful_refresh: "2026-07-16T10:00:00Z",
  items: [
    {
      id: "fixture-project",
      name: "Temporary project",
      path: "C:\\Temp\\pytest\\repository",
      favorite: false,
      tags: ["frontend"],
      notes: "Artificial fixture notes",
      archived: false,
      exists: true,
      is_git_repository: true,
      branch: "main",
      tracking_branch: "origin/main",
      status: "clean",
      changed_files: 0,
      modified_count: 0,
      staged_count: 0,
      untracked_count: 0,
      ahead_count: 0,
      behind_count: 0,
      last_commit_message: "Initial fixture",
      last_commit_author: "Test User",
      last_commit_date: "2026-07-16T09:00:00Z",
      repository_age_days: 0,
      recent_activity: true,
      primary_technology: "React",
      technologies: ["React", "TypeScript"],
      health_score: 86,
      warning_count: 0,
      last_scan_duration_ms: 12,
      last_scan_timestamp: "2026-07-16T10:00:00Z",
      error: null,
    },
  ],
};

const activity: ActivityList = {
  items: [
    {
      id: "event-1",
      timestamp: "2026-07-16T10:00:00Z",
      kind: "success",
      event_type: "scan_completed",
      message: "Repository refresh completed (1 detected)",
      project_id: null,
    },
  ],
};

const settings: Settings = {
  schema_version: 4,
  onboarding_completed: true,
  projects: [
    {
      name: "Temporary project",
      path: "C:\\Temp\\pytest\\repository",
      favorite: false,
      tags: ["frontend"],
      notes: "Artificial fixture notes",
      archived: false,
    },
  ],
  scan_roots: [],
  ignored_directories: [],
  maximum_scan_depth: 3,
  maximum_repositories_per_root: 100,
  maximum_directories_per_scan: 5000,
  scan_timeout_seconds: 20,
  cache_duration_seconds: 30,
  refresh_interval_seconds: 300,
  maximum_commits_displayed: 5,
  appearance: "light",
  start_minimized: false,
  reduced_motion: false,
  confirm_before_removing_project: true,
  log_level: "INFO",
  default_landing_page: "overview",
  date_time_display: "local",
  table_density: "comfortable",
  stale_project_days: 30,
  default_sort: "name",
  notification_preferences: {},
  notification_severity_threshold: "warning",
  notification_history_length: 200,
  saved_views: [],
  active_saved_view: null,
};

export function successfulProvider(): DataProvider {
  return {
    getSystemSummary: async () => systemSummary,
    getProjects: async () => projects,
    getProject: async () => ({
      summary: projects.items[0],
      modified_files: [],
      staged_files: [],
      untracked_files: [],
      important_files: ["README.md"],
      root_files: ["README.md"],
      dependency_manager: "npm",
      testing_framework: "Vitest",
      ci_provider: "GitHub Actions",
      container_support: false,
      deployment_indicators: [],
      monorepo: false,
      application_directories: ["src"],
      documentation_directory: false,
      remote_present: true,
      commits: [],
      health_breakdown: [],
      warnings: [],
      warning_details: [],
    }),
    previewProject: async () => ({
      summary: projects.items[0],
      modified_files: [],
      staged_files: [],
      untracked_files: [],
      important_files: [],
      root_files: [],
      dependency_manager: null,
      testing_framework: null,
      ci_provider: null,
      container_support: false,
      deployment_indicators: [],
      monorepo: false,
      application_directories: [],
      documentation_directory: false,
      remote_present: false,
      commits: [],
      health_breakdown: [],
      warnings: [],
      warning_details: [],
    }),
    previewRoot: async () => projects,
    addProjects: async () => settings,
    removeProject: async () => settings,
    updateProjectPath: async () => settings,
    updateProject: async () => settings,
    refreshProjects: async () => projects,
    getActivity: async () => activity,
    clearActivity: async () => undefined,
    getSettings: async () => settings,
    updateSettings: async () => settings,
    getQaStatus: async () => ({
      enabled: false,
      artificial_data: false,
      data_root: null,
      test_lab: null,
    }),
    resetQaData: async () => settings,
    regenerateQaData: async () => settings,
    getSafeDiagnostics: async () => ({
      devpulse_version: "0.3.0-alpha.1",
      operating_system: "Windows 11",
      qa_mode: false,
      local_core_status: "connected",
      sidecar_status: "running",
      startup_duration_ms: 120,
      last_scan_status: "completed",
      registered_projects: 1,
      cache_status: "ready",
      configuration_schema_version: 4,
      data_boundary: "DevPulse application data",
      recent_error_codes: [],
      log_excerpt: ["INFO: Local core started"],
    }),
    exportSafeDiagnostics: async () => '{"local_core_status":"connected"}\n',
    getSystemHistory: async () => ({ items: [] }),
    exportConfiguration: async () => ({
      schema_version: 4,
      exported_at: "2026-07-16T10:00:00Z",
      includes_notes: false,
      settings: {},
      projects: [],
    }),
    previewConfigurationImport: async () => ({
      additions: [],
      updates: [],
      conflicts: [],
      valid: true,
    }),
    importConfiguration: async () => settings,
    getBackups: async () => [],
    createBackup: async () => ({
      id: "20260716T100000Z-abcdef12",
      created_at: "2026-07-16T10:00:00Z",
      size_bytes: 100,
      source: "manual",
    }),
    restoreBackup: async () => settings,
    deleteBackup: async () => undefined,
  };
}
